# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75d0cfcda1715eb360a67b3390d6f703abd83efb11fdf26a0c4ae51a3ef5f116d11625311bdb53d04211cf972ce3b47e8d3adc509809a9357128a9261357b015
  admin_name: "Test"
  admin_email: "mathieul3257@gmail.com"
  admin_password: "roadrunner19"
  email_provider_username: "mathieul3257@gmail.com"
  email_provider_password: "roadrunner19"
  domain_name: "localhost:3000"
  email_from: "Confirmation inscription Emplois Stage"

test:
  secret_key_base: 4620551bda6eaf08c53d35b8ad09e7269a5647438b74a688be47b787f46af1995d505706da9f88733334288d7745d169b4d811730990c27d7c703c66e987d4b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_name: "Test"
  admin_email: "mathieul3257@gmail.com"
  admin_password: "roadrunner19"
  email_provider_username: "mathieul3257@gmail.com"
  email_provider_password: "roadrunner19"
  domain_name: "localhost:3000"
  email_from: "Confirmation inscription Emplois Stage"
